Check ofr *medn.nii.gz file on exit

diff --git a/run b/run
--- a/run
+++ b/run
@@ -6,9 +6,10 @@ export PYTHON_PATH=$PYTHON_PATH:/flywheel/v0/me-ica/
 python /flywheel/v0/run_meica.py
 exit_status=$?
 killall Xvfb
-if [[ $exit_status == "0" ]]; then
+if [[ $exit_status == "0" ]] && [[ -n $(find /flywheel/v0/output/* -name "*medn.nii.gz") ]]; then
   echo -e "MEICA success! (exit code = $exit_status)"
+  exit 0
 else
-  echo -e "MEICA exited with non-zero status! (exit code = $exit_status)"
+  echo -e "Errors detected (exit code = $exit_status)"
+  exit 1
 fi
-exit $exit_status
